<?php include'header.php';?>
<title>Хобби</title>
<div class=el style="padding:25px; min-width:720px;"><p class="zagolovokn">Моё хобби - это заказ товаров из Китая</p>
<img class="newim" style="padding-right:25px; padding-top:15px;" src="http://neformat.dn.ua/wp-content/uploads/2012/09/china_made.jpg">
<p style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;">Это очень выгодно, так как в последнее время наблюдается подъём цен на российские и зарубежные товары, но не на товары из Китая: ведь нам не приходится переплачивать за бренд.<br>Многие опасаются низкого качества китайских товаров. Но хочу вас заверить: уровень китайской промышленности (особенно, электроники), уже давно вышел на флагманский уровень, а качество продуктов, например, Xiaomi, ничуть не уступает решениям от Samsung или  Apple. <br> Конечно, есть и no-name промышленность, когда дядушка Ляо-Дзяду в своём подвальчике собирает на коленке "IPhone 9S", но от таких товаров стоит отказаться.</p></div>
<div class=el style="padding:25px; min-width:720px;"><p class="zagolovokn">Магазины</p>
<img class="newim" style="padding-right:25px; padding-top:15px;" src="http://epicblog.ru/wp-content/uploads/2014/11/aliexpress-kak-kupit.jpg">
<p style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;">Я рекомендую вам для личных заказов использовать китайскую интренет-площадку Aliexpress. У него есть ряд неоспоримых преимуществ, таких как: <ul style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;"><li>Полная защита покупателя, пока вы не получите товар</li><li>Вы можете открыт спор с продавцом и вернуть свои деньги, если вам не понравилось качество товара</li><li>Многие продавцы, борясь за хорошие отзывы, вкладывают различные "подарки"</li><li>Ну, и самое главное - это одни из самых низких цен + постоянные акции и скидки</li></ul></p></div>
<div class=el style="padding:25px; min-width:720px;"><p class="zagolovokn">Мои последние покупки</p>
<img class="newim" style="padding-right:25px; padding-top:15px;" src="http://www.tpp-inform.ru/userdata/1334256963_1.gif">
<p style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;">На данный момент, количество заказов в мом личном кабинете приближается к 50.<br> Основной перечень моих заказов - это различная электронника: <ul style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;"><li>Несколько телефонов (себе, и друзьям, <font color=red>которые не умеют пользоваться интернетом</font>)<li>Два экрана для своего телефона (<font color=red>спасибо моим кривым ручкам</font>)</li><li>Куча наушников</li><li>Множество аксессуаров(usb-кабели, защитные плёнки, чехлы)</li><li>Усиленные и внешние батареи</li></ul></p></div>
<div class=el style="padding:25px; min-width:720px;"><p class="zagolovokn">О спорах (<font color=red>dispute</font>)</p>
<img class="newim" style="padding-right:25px; padding-top:15px;" src="http://3e.img.v4.skyrock.net/9582/46539582/pics/2162362729_small_1.jpg">
<p style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;">В любой момент, начиная с вашей оплаты и до подтверждения получения и удволетворённости товаром, вы можете открыть с продавцом спор и вернуть часть своих денег, или даже всю сумму:<ul style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;"><li>Если товар не пришёл в указанный срок - продавец взращает вам всю сумму или отправляет новый заказ</font>)<li>Товар пришёл бракованный/разбитый/пришёл камень вместо айфона... - в зависимости от ситуации - часть или вся сумма</li><li>Не тот цвет/комплектация - продавец вернёт часть денег</li><li>Если вам просто не понравился товар, и вы сможете убедить продавца, что он плох - тоже можно вернуть часть денег ;-)</li></ul></p></div>
<div class=el style="padding:25px; min-width:720px;"><p class="zagolovokn">Я получил посылку, что делать?</p>
<img class="newim" style="padding-right:25px; padding-top:15px;" src="http://www.tmnpost.ru/photo/uzn_1333977216.jpg">
<p style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;">В любой момент, начиная с вашей оплаты и до подтверждения получения и удволетворённости товаром, вы можете открыть с продавцом спор и вернуть часть своих денег, или даже всю сумму:<ol style="text-align:justify; font-size:17px; margin-bottom:0; padding:0px;"><li>В первую очередь снимите распаковку посылки на камеру, предварительно показав, что она запечатана<li>Когда вы вскроете посылку, достаньте товар и проверьте его целостность, функционал и комплектацию</li><li>Если всё хорошо - вы можете в личном кабинете подтвердить получение товара и поблагодарть продавца, оставив ему положительный отзыв</li><li>Если товар оказался плох по одному из вышеперечисленных пунктов - то идёте открывать спор, прикрепив видео с распаковкой, после чего ждите встречного предложения или возврата денег)</li></ol></p></div>
<div class=el style="padding:25px; min-width:720px; min-height:370px;"><p style="font-size:25px;" class="zagolovokn">Спасибо за прочтение, теперь вы познакомились с моим хобби, и можете сами попробовать сделать свой первый заказ на Aliexpress</p>
<img class="newim" style="position:absolute; left:0; right:0; margin:0 auto;" src="http://vera-vasilyeva.ru/files/c45/c45c2a79e89f57671cb607077bbdb942.jpg">
</div>
<?php include'footer.php';
?>